# Generated by Django 4.0.6 on 2022-07-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatives',
            name='age',
            field=models.IntegerField(),
        ),
    ]
